-- Add dimension columns to products table
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS length DECIMAL(10,2) DEFAULT 10,
ADD COLUMN IF NOT EXISTS breadth DECIMAL(10,2) DEFAULT 10,
ADD COLUMN IF NOT EXISTS height DECIMAL(10,2) DEFAULT 10;
