'use client'

import React from 'react'
import { FileCheck, Activity, CreditCard, AlertTriangle } from 'lucide-react'

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-white">
            <section className="bg-emerald-900 py-16 px-4">
                <div className="max-w-4xl mx-auto text-center">
                    <h1 className="text-3xl md:text-5xl font-bold text-white mb-4">Terms of Service</h1>
                    <p className="text-emerald-100 opacity-80">By using D2BCart, you agree to these legal conditions.</p>
                </div>
            </section>

            <section className="py-20 px-4">
                <div className="max-w-4xl mx-auto">
                    <div className="prose prose-emerald max-w-none space-y-12">
                        <section className="space-y-4">
                            <h2 className="text-2xl font-bold text-gray-900 flex items-center gap-3">
                                <FileCheck className="w-7 h-7 text-emerald-600" />
                                1. User Registration & Eligibility
                            </h2>
                            <p className="text-gray-600 leading-relaxed">
                                You must be a valid business entity or business owner representing a retail store or manufacturing facility. For manufacturers, a valid GSTIN and business address proof are mandatory before listing products. Retailers must provide valid KYC documents upon request.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-2xl font-bold text-gray-900 flex items-center gap-3">
                                <Activity className="w-7 h-7 text-emerald-600" />
                                2. Platform Usage & Conduct
                            </h2>
                            <p className="text-gray-600 leading-relaxed">
                                Users agree not to attempt to circumvent the platform to close deals offline. Any misuse of contact information, spamming, or fraudulent listing will result in immediate termination of account and legal action where applicable.
                            </p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-2xl font-bold text-gray-900 flex items-center gap-3">
                                <CreditCard className="w-7 h-7 text-emerald-600" />
                                3. Payments, Taxes & Commission
                            </h2>
                            <p className="text-gray-600 leading-relaxed">
                                D2BCart handles payments through an escrow-like model. Payments are held by our partner gateway and released to manufacturers after order dispatch. D2BCart charges a platform service fee on every successful transaction.
                            </p>
                            <ul className="list-disc pl-6 text-gray-600 space-y-2">
                                <li>The prices listed by manufacturers must include applicable GST.</li>
                                <li>Retailers are responsible for paying shipping costs as calculated by Shiprocket.</li>
                                <li>Invoices generated by the platform are legally binding documents.</li>
                            </ul>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-2xl font-bold text-gray-900 flex items-center gap-3">
                                <AlertTriangle className="w-7 h-7 text-emerald-600" />
                                4. Limitation of Liability
                            </h2>
                            <p className="text-gray-600 leading-relaxed">
                                D2BCart acts as a marketplace facilitator. We are not responsible for the quality of goods produced by manufacturers or delays caused by third-party logistics providers. However, we provide mediation for disputes between parties.
                            </p>
                        </section>

                        <div className="bg-gray-50 rounded-[2rem] p-8 border border-gray-100 italic text-gray-500 text-sm">
                            Please note that these terms are subject to change without prior notice. Continued use of the platform after changes constitutes acceptance of the new terms.
                        </div>
                    </div>
                </div>
            </section>
        </div>
    )
}
